onlyBuiltDependencies:
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver
  - workerd

overrides:
  "@eslint/plugin-kit@<0.3.4": ">=0.3.4"
  astro@<5.14.3: ">=5.14.3"
  astro@>=5.0.0-alpha.0 <=5.13.0: ">=5.13.2"
  astro@>=5.2.0 <5.12.8: ">=5.12.8"
  devalue@<5.3.2: ">=5.3.2"
  form-data@>=4.0.0 <4.0.4: ">=4.0.4"
  playwright@<1.55.1: ">=1.55.1"
  vite@>=6.0.0 <=6.3.5: ">=6.3.6"
  vite@>=6.0.0 <=6.4.0: ">=6.4.1"
