onlyBuiltDependencies:
  - esbuild
  - lefthook
  - sharp
  - unrs-resolver
  - workerd

overrides:
  "@eslint/plugin-kit@<0.3.4": ">=0.3.4"
  "@isaacs/brace-expansion@<=5.0.0": ">=5.0.1"
  ajv@<6.14.0: ">=6.14.0"
  ajv@>=7.0.0-alpha.0 <8.18.0: ">=8.18.0"
  astro@<5.14.3: ">=5.14.3"
  astro@>=5.0.0-alpha.0 <=5.13.0: ">=5.13.2"
  astro@>=5.2.0 <5.12.8: ">=5.12.8"
  devalue@<5.3.2: ">=5.3.2"
  devalue@<=5.6.2: ">=5.6.3"
  fast-xml-parser@<5.3.8: ">=5.3.8"
  fast-xml-parser@>=4.1.3 <5.3.5: ">=5.3.5"
  fast-xml-parser@>=4.1.3 <5.3.6: ">=5.3.6"
  fast-xml-parser@>=5.0.9 <=5.3.3: ">=5.3.4"
  form-data@>=4.0.0 <4.0.4: ">=4.0.4"
  glob@>=10.2.0 <10.5.0: ">=10.5.0"
  h3@<=1.15.4: ">=1.15.5"
  js-yaml@>=4.0.0 <4.1.1: ">=4.1.1"
  lodash@>=4.0.0 <=4.17.22: ">=4.17.23"
  minimatch@<3.1.3: ">=3.1.3"
  minimatch@>=10.0.0 <10.2.1: ">=10.2.1"
  minimatch@>=9.0.0 <9.0.6: ">=9.0.6"
  playwright@<1.55.1: ">=1.55.1"
  rollup@>=4.0.0 <4.59.0: ">=4.59.0"
  undici@<6.23.0: ">=6.23.0"
  undici@>=7.0.0 <7.18.2: ">=7.18.2"
  vite@>=6.0.0 <=6.3.5: ">=6.3.6"
  vite@>=6.0.0 <=6.4.0: ">=6.4.1"
  wrangler@>=4.0.0 <4.59.1: ">=4.59.1"
