name: "Setup Node.js and pnpm"
description: "Setup Node.js, pnpm, and restore caches"

inputs:
  turbo-cache-key:
    description: "Cache key for Turborepo"
    required: true
  node-modules-cache-key:
    description: "Cache key for node_modules"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check if node_modules cache exists
      id: check-node-modules-cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          */node_modules
        key: ${{ inputs.node-modules-cache-key }}
        lookup-only: true

    - name: Restore node_modules cache
      if: steps.check-node-modules-cache.outputs.cache-hit != 'true'
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          */node_modules
        key: ${{ inputs.node-modules-cache-key }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Setup pnpm
      if: steps.check-node-modules-cache.outputs.cache-hit != 'true'
      uses: pnpm/action-setup@v4
      with:
        version: 10.11.0
        run_install: false

    - name: Install dependencies
      if: steps.check-node-modules-cache.outputs.cache-hit != 'true'
      shell: bash
      run: pnpm install --frozen-lockfile
