name: "Setup Bun with Cache"
description: "Setup Bun, restore caches, and install dependencies"

inputs:
  cache-suffix:
    description: 'Suffix for the cache key (e.g., "build", "playwright")'
    required: true
  enable-astro-cache:
    description: "Whether to enable Astro cache restoration"
    required: false
    default: "false"
  bun-version:
    description: "Bun version to install"
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Restore Turborepo Cache
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ inputs.cache-suffix }}-${{ hashFiles('**/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-turbo-${{ inputs.cache-suffix }}-
          ${{ runner.os }}-turbo-

    - name: Restore Astro Cache
      if: inputs.enable-astro-cache == 'true'
      uses: actions/cache@v4
      with:
        path: |
          .astro
          node_modules/.astro
        key: ${{ runner.os }}-astro-${{ hashFiles('**/bun.lock') }}
        restore-keys: ${{ runner.os }}-astro-

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Install dependencies
      shell: bash
      run: bun install --frozen-lockfile
