name: "Run Playwright Tests"
description: "Run Playwright end-to-end tests"

runs:
  using: "composite"
  steps:
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install Playwright Browsers
      shell: bash
      run: pnpm exec playwright install --with-deps

    - name: Download build output
      uses: actions/download-artifact@v4
      with:
        name: build
        path: dist

    - name: Run Playwright tests
      shell: bash
      run: pnpm exec turbo run test:playwright
