name: Upload to B-Backup (Manual)

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: get pnpm
        run: npm install -g pnpm

      - name: double check xD
        run: pnpm --version

      - name: get dependencies
        run: pnpm i

      - name: buld
        run: pnpm run build

      - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.4
        with:
          source: 'dist'
          destination: ''
          storageZoneName: '${{ secrets.STORAGE_NAME_BACKUP }}'
          storagePassword: '${{ secrets.STORAGE_PASSWORD_BACKUP }}'
          upload: 'true'
          remove: 'false'
          purgePullZone: 'false'
